/*
 * Copyright (c) 
 */

#ifndef ASTRO_EDDY_CURRENT_HPP
#define ASTRO_EDDY_CURRENT_HPP

#include <SML/linearAlgebra.hpp>

namespace astro
{

//! Compute eddy current torque.
/*!
 * Computes the eddy current torque on a certain object generated by an external source. The model
 * for the torque is given by
 *
 * \f[
 *      \vec{T}_{eddy} = \vec{m} \times \vec{B}
 * \f]
 * 
 * where \f$\vec{m}\f$ is the magnetic moment of the object and \f$\vec{B}\f$ is the magnetic field
 * generated by an external source.
 *      
 * @param  magneticMoment    Magnetic Moment         [A * m^2]
 * @param  magneticField     Magnetic Field          [T]
 * @return                   Eddy Current Torque     [N * m]                     
 */
 template< typename Vector3 >
 Vector3 computeEddyTorque( const Vector3&  magneticMoment, 
                            const Vector3&  magneticField ); 

  //! Compute eddy current torque.
 template< typename Vector3 >
  Vector3 computeEddyTorque( const Vector3&  magneticMoment, 
                             const Vector3&  magneticField )

 {
    // Compute the eddy current torque.
    return sml::cross< Vector3 >( magneticMoment, magneticField);
 }

 } // namespace astro

 #endif // ASTRO_EDDY_CURRENT_HPP