astro: astro Namespace Reference
astro Namespace Reference
Enumerations
enum CartesianElementIndices {
xPositionIndex = 0 , yPositionIndex = 1 , zPositionIndex = 2 , xVelocityIndex = 3 ,
yVelocityIndex = 4 , zVelocityIndex = 5
}
Cartesian element array indices.
enum KeplerianElementIndices {
semiMajorAxisIndex = 0 , semiLatusRectumIndex = 0 , eccentricityIndex = 1 , inclinationIndex = 2 ,
argumentOfPeriapsisIndex = 3 , longitudeOfAscendingNodeIndex = 4 , trueAnomalyIndex = 5 , trueLongitudeOfPeriapsis = 5 ,
argumentOfLatitude = 5 , trueLongitude = 5 , meanAnomalyIndex = 5
}
Keplerian element array indices.
Functions
template<typename Real , typename Vector3 >
Vector3 computeCentralBodyAcceleration (const Real gravitationalParameter, const Vector3 &position)
Compute the acceleration of a point mass body orbiting a uniform central body.
template<typename Real , typename Vector3 >
Vector3 computeJ2Acceleration (const Real gravitationalParameter, const Vector3 &position, const Real equatorialRadius, const Real j2Coefficient)
Compute gravitational acceleration due to J2.
template<typename Real , typename Vector6 >
Vector6 convertCartesianToKeplerianElements (const Vector6 &cartesianElements, const Real gravitationalParameter, const Real tolerance=10.0 *std::numeric_limits< Real >::epsilon())
Convert Cartesian elements to Keplerian elements.
template<typename Real , typename Vector6 >
Vector6 convertKeplerianToCartesianElements (const Vector6 &keplerianElements, const Real gravitationalParameter, const Real tolerance=10.0 *std::numeric_limits< Real >::epsilon())
Convert Keplerian elements to Cartesian elements.
template<typename Real >
Real convertTrueAnomalyToEllipticalEccentricAnomaly (const Real trueAnomaly, const Real eccentricity)
Convert true anomaly to elliptical eccentric anomaly.
template<typename Real >
Real convertTrueAnomalyToHyperbolicEccentricAnomaly (const Real trueAnomaly, const Real eccentricity)
Convert true anomaly to hyperbolic eccentric anomaly.
template<typename Real >
Real convertTrueAnomalyToEccentricAnomaly (const Real trueAnomaly, const Real eccentricity)
Convert true anomaly to eccentric anomaly.
template<typename Real >
Real convertEllipticalEccentricAnomalyToMeanAnomaly (const Real ellipticalEccentricAnomaly, const Real eccentricity)
Convert elliptical eccentric anomaly to mean anomaly.
template<typename Real >
Real convertHyperbolicEccentricAnomalyToMeanAnomaly (const Real hyperbolicEccentricAnomaly, const Real eccentricity)
Convert hyperbolic eccentric anomaly to mean anomaly.
template<typename Real >
Real convertEccentricAnomalyToMeanAnomaly (const Real eccentricAnomaly, const Real eccentricity)
Convert eccentric anomaly to mean anomaly.
template<typename Real >
Real convertEllipticalEccentricAnomalyToTrueAnomaly (const Real ellipticEccentricAnomaly, const Real eccentricity)
Convert elliptical eccentric anomaly to true anomaly.
template<typename Real >
Real convertHyperbolicEccentricAnomalyToTrueAnomaly (const Real hyperbolicEccentricAnomaly, const Real eccentricity)
Convert hyperbolic eccentric anomaly to true anomaly.
template<typename Real >
Real convertEccentricAnomalyToTrueAnomaly (const Real eccentricAnomaly, const Real eccentricity)
Convert eccentric anomaly to true anomaly.
template<typename Real >
Real computeEllipticalKeplerFunction (const Real eccentricAnomaly, const Real eccentricity, const Real meanAnomaly)
Compute Kepler function for elliptical orbits.
template<typename Real >
Real computeFirstDerivativeEllipticalKeplerFunction (const Real eccentricAnomaly, const Real eccentricity)
Compute 1st-derivative of Kepler function for elliptical orbits.
template<typename Real , typename Integer >
Real convertEllipticalMeanAnomalyToEccentricAnomaly (const Real eccentricity, const Real meanAnomaly, const Real rootFindingTolerance=1.0e-3 *std::numeric_limits< Real >::epsilon(), const Integer maximumIterations=100)
Convert elliptical mean anomaly to eccentric anomaly.
template<typename Real >
Real computeAbsorptionRadiationPressure (const Real energyFlux)
Compute radiation pressure for complete absorption.
template<typename Real >
Real computeRadiationPressure (const Real referenceRadiationPressure, const Real referenceDistance, const Real distance)
Compute radiation pressure.
template<typename Real , typename Vector3 >
Vector3 computeCannonballRadiationPressureAcceleration (const Real radiationPressure, const Real radiationPressureCoefficient, const Vector3 &unitVectorToSource, const Real radius, const Real bulkDensity)
Compute radiation pressure acceleration for a cannonball.
template<typename Real , typename Vector3 >
Vector3 computeCannonballPoyntingRobertsonDragAcceleration (const Real radiationPressure, const Real radiationPressureCoefficient, const Vector3 &unitVectorToSource, const Real radius, const Real bulkDensity, const Vector3 &velocity)
Compute Poynting-Roberson drag acceleration for a cannonball.
template<typename Real >
Real computeKeplerMeanMotion (const Real semiMajorAxis, const Real gravitationalParameterOfCentralBody, const Real massOfOrbitingBody=0.0)
Compute mean motion.
template<typename Real >
Real computeKeplerOrbitalPeriod (const Real semiMajorAxis, const Real gravitationalParameterOfCentralBody, const Real massOfOrbitingBody=0.0)
Compute orbital period.
template<typename Real >
Real computeCircularVelocity (const Real semiMajorAxis, const Real gravitationalParameterOfCentralBody)
Compute circular velocity.
Variables
static const double ASTRO_GRAVITATIONAL_CONSTANT = 6.67259e-11
Gravitational constant [m^3 s^-2] (Standish, 1995).
static const double ASTRO_JULIAN_DAY_IN_SECONDS = 86400.0
Julian day in seconds (NASA, 2012).
static const double ASTRO_JULIAN_YEAR_IN_DAYS = 365.25
Julian year in days (NASA, 2012).
static const double ASTRO_JULIAN_YEAR_IN_SECONDS = 3.15576e7
Julian year in seconds.
static const double ASTRO_AU_IN_KM = 149597870.7
Astronautical Unit in km (NASA, 2012).
static const double ASTRO_GREGORIAN_EPOCH_IN_JULIAN_DAYS = 1721425.5
Start of Gregorian epoch in Julian days (Ramsey, 2016).
static const double ASTRO_SPEED_OF_LIGHT = 299792458.0
Speed of light [m s^-1] (Wikipedia, 2018).
Enumeration Type Documentation
CartesianElementIndices
enum astro::CartesianElementIndices
Enumerator
xPositionIndex
yPositionIndex
zPositionIndex
xVelocityIndex
yVelocityIndex
zVelocityIndex
Definition at line 13 of file stateVectorIndices.hpp.
KeplerianElementIndices
enum astro::KeplerianElementIndices
Enumerator
semiMajorAxisIndex
semiLatusRectumIndex
eccentricityIndex
inclinationIndex
argumentOfPeriapsisIndex
longitudeOfAscendingNodeIndex
trueAnomalyIndex
trueLongitudeOfPeriapsis
argumentOfLatitude
trueLongitude
meanAnomalyIndex
Definition at line 24 of file stateVectorIndices.hpp.
Function Documentation
computeCentralBodyAcceleration()
template<typename Real , typename Vector3 > Vector3 astro::computeCentralBodyAcceleration (const Real gravitationalParameter, const Vector3 & position)
Computes the acceleration of a point mass body orbiting a uniform central body based on Newton's second law and his law of gravitation.
The expression of this acceleration is based on the two-body equation of motion, which represents the relative equation of motion of a body as it orbits the central body:
where is a gravitational parameter (e.g., in the case of the Earth), is the distance from the origin of the reference frame to the body (i.e., the magnitude of the position vector), and is the position vector of the body relative to the origin of the reference frame.
Template Parameters
Real Real type
Vector3 3-vector type
Parameters
[in] gravitationalParameter Gravitational parameter of central body [km^3 s^-2]
[in] position Position vector of the orbiting body [km]
Returns
Acceleration vector [km s^-2]
Definition at line 41 of file centralBodyAccelerationModel.hpp.
computeJ2Acceleration()
template<typename Real , typename Vector3 > Vector3 astro::computeJ2Acceleration (const Real gravitationalParameter, const Vector3 & position, const Real equatorialRadius, const Real j2Coefficient)
Compute gravitational acceleration at given position vector subject to an irregular gravity field. The acceleration due to the J2-coefficient is given by (Melman, 2012):
where is the gravitational parameter of the central body, , , and are the Cartesian position components, is the radial position, and is the second zonal coefficient of the gravity field.
The positions and accelerations are given with respect to an inertial (barycentric) reference frame.
Template Parameters
Real Real type
Vector Vector type
Parameters
[in] position Position vector of body subject to J2-acceleration [m]
[in] gravitationalParameter Gravitational parameter of central body [m^3 s^-2]
[in] equatorialRadius Equatorial radius of central body, in formulation of spherical harmonics expansion [m]
[in] j2Coefficient Unnormalized J2-coefficient of spherical harmonics expansion [-]
Returns
J2 gravitational acceleration [m s^-2]
Definition at line 47 of file j2AccelerationModel.hpp.
convertCartesianToKeplerianElements()
template<typename Real , typename Vector6 > Vector6 astro::convertCartesianToKeplerianElements (const Vector6 & cartesianElements, const Real gravitationalParameter, const Real tolerance = 10.0 * std::numeric_limits<Real>::epsilon())
Converts a given set of Cartesian elements (position, velocity) to classical (osculating) Keplerian elements. See Vallado (2007) for a derivation of the conversion.
The tolerance is set to a default value. It should not be changed unless required for specific scenarios. Below this tolerance value for eccentricity and inclination, the orbit is considered to be a limit case.
Essentially, special solutions are then used for parabolic, circular inclined, non-circular equatorial, and circular equatorial orbits. These special solutions are required because of singularities in the classical Keplerian elements. If high precision is required near these singularities, users are encouraged to consider using other elements, such as Modified Equinoctial Elements (MEE). It should be noted that MEE also suffer from singularities, but not for zero eccentricity and inclination.
WARNING: If eccentricity is 1.0 within tolerance, keplerianElements(0) = semi-latus rectum, since the orbit is parabolic. WARNING: If eccentricity is 0.0 within tolerance, argument of periapsis is set to NaN, since the orbit is circular. WARNING: If inclination is 0.0 within tolerance, longitude of ascending node is set to NaN, since since the orbit is equatorial. WARNING: If inclination is 0.0 within tolerance, longitude of ascending node is set to NaN, since since the orbit is equatorial. WARNING: If eccentricity = 0.0 within tolerance, inclination = non-zero keplerianElements(5) = argument of latitude WARNING: If eccentricity = non-zero, inclination = 0.0 within tolerance keplerianElements(5) = true longitude of periapsis WARNING: If eccentricity = 0.0 within tolerance, inclination = 0.0 within tolerance keplerianElements(5) = true latitude
Template Parameters
Real Real type
Vector Vector type
Parameters
cartesianElements Vector containing Cartesian elements
N.B.: Order of elements is important!
cartesianElements(0) = x-position coordinate [m]
cartesianElements(1) = y-position coordinate [m]
cartesianElements(2) = z-position coordinate [m]
cartesianElements(3) = x-velocity coordinate [m/s]
cartesianElements(4) = y-velocity coordinate [m/s]
cartesianElements(5) = z-velocity coordinate [m/s]
gravitationalParameter Gravitational parameter of central body [m^3 s^-2]
tolerance Tolerance used to check for limit cases (eccentricity, inclination)
Returns
Converted vector of Keplerian elements
N.B.: Order of elements is important!
keplerianElements(0) = semiMajorAxis [m]
keplerianElements(1) = eccentricity [-]
keplerianElements(2) = inclination [rad]
keplerianElements(3) = argument of periapsis [rad]
keplerianElements(4) = longitude of ascending node [rad]
keplerianElements(5) = true anomaly [rad]
Definition at line 79 of file orbitalElementConversions.hpp.
References argumentOfLatitude, trueLongitude, trueLongitudeOfPeriapsis, xPositionIndex, xVelocityIndex, yPositionIndex, yVelocityIndex, zPositionIndex, and zVelocityIndex.
convertKeplerianToCartesianElements()
template<typename Real , typename Vector6 > Vector6 astro::convertKeplerianToCartesianElements (const Vector6 & keplerianElements, const Real gravitationalParameter, const Real tolerance = 10.0 * std::numeric_limits<Real>::epsilon())
Converts a given set of Keplerian (osculating) elements to Cartesian elements (position, velocity). See Chobotov (2006) for a full derivation of the conversion.
WARNING: If eccentricity is 1.0 within tolerance, the user should provide keplerianElements(0) = semi-latus rectum, since the orbit is parabolic.
Template Parameters
Real Real type
Vector Vector type
Parameters
keplerianElements Vector containing Keplerian elemenets
N.B.: Order of elements is important!
keplerianElements(0) = semiMajorAxis [m]
keplerianElements(1) = eccentricity [-]
keplerianElements(2) = inclination [rad]
keplerianElements(3) = argument of periapsis [rad]
keplerianElements(4) = longitude of [rad] ascending node [rad]
keplerianElements(5) = true anomaly [rad]
gravitationalParameter Gravitational parameter of central body [m^3 s^-2]
tolerance Tolerance used to check for limit case of eccentricity
Returns
Converted vector of Cartesian elements
N.B.: Order of elements is important!
cartesianElements(0) = x-position coordinate [m]
cartesianElements(1) = y-position coordinate [m]
cartesianElements(2) = z-position coordinate [m]
cartesianElements(3) = x-velocity coordinate [m/s]
cartesianElements(4) = y-velocity coordinate [m/s]
cartesianElements(5) = z-velocity coordinate [m/s]
Definition at line 316 of file orbitalElementConversions.hpp.
References argumentOfPeriapsisIndex, eccentricityIndex, inclinationIndex, longitudeOfAscendingNodeIndex, semiMajorAxisIndex, trueAnomalyIndex, xPositionIndex, xVelocityIndex, yPositionIndex, yVelocityIndex, zPositionIndex, and zVelocityIndex.
convertTrueAnomalyToEllipticalEccentricAnomaly()
template<typename Real > Real astro::convertTrueAnomalyToEllipticalEccentricAnomaly (const Real trueAnomaly, const Real eccentricity)
Converts true anomaly to eccentric anomaly for elliptical orbits (0 <= eccentricity < 1.0).
This implementation performs a check on the eccentricity and throws an error if it is non-elliptical, i.e., eccentricity < 0.0 and eccentricity >= 1.0.
The equations used can be found in (Chobotov, 2002).
Template Parameters
Real Real type
Parameters
trueAnomaly True anomaly [rad]
eccentricity Eccentricity [-]
Returns
Elliptical eccentric anomaly [rad]
Definition at line 420 of file orbitalElementConversions.hpp.
Referenced by convertTrueAnomalyToEccentricAnomaly().
convertTrueAnomalyToHyperbolicEccentricAnomaly()
template<typename Real > Real astro::convertTrueAnomalyToHyperbolicEccentricAnomaly (const Real trueAnomaly, const Real eccentricity)
Converts true anomaly to hyperbolic eccentric anomaly for hyperbolic orbits (eccentricity > 1.0).
This implementation performs a check on the eccentricity and throws an error if it is non-hyperbolic, i.e., eccentricity >= 1.0.
The equations used can be found in (Chobotov, 2002).
Template Parameters
Real Real type
Parameters
trueAnomaly True anomaly [rad]
eccentricity Eccentricity [-]
Returns
Hyperbolic eccentric anomaly [rad]
Definition at line 453 of file orbitalElementConversions.hpp.
Referenced by convertTrueAnomalyToEccentricAnomaly().
convertTrueAnomalyToEccentricAnomaly()
template<typename Real > Real astro::convertTrueAnomalyToEccentricAnomaly (const Real trueAnomaly, const Real eccentricity)
Converts true anomaly to eccentric anomaly for elliptical and hyperbolic orbits (eccentricity < 1.0 && eccentricity > 1.0). This function is essentially a wrapper for functions that treat each case. It should be used in cases where the eccentricity of the orbit is not known a priori.
This implementation performs a check on the eccentricity and throws an error for eccentricity < 0.0 and parabolic orbits, which have not been implemented.
The equations used can be found in (Chobotov, 2002).
See also
convertTrueAnomalyToEllipticalEccentricAnomaly, convertTrueAnomalyToHyperbolicEccentricAnomaly
Template Parameters
Real Real type
Parameters
trueAnomaly True anomaly [rad]
eccentricity Eccentricity [-]
Returns
Eccentric anomaly [rad]
Definition at line 495 of file orbitalElementConversions.hpp.
References convertTrueAnomalyToEllipticalEccentricAnomaly(), and convertTrueAnomalyToHyperbolicEccentricAnomaly().
convertEllipticalEccentricAnomalyToMeanAnomaly()
template<typename Real > Real astro::convertEllipticalEccentricAnomalyToMeanAnomaly (const Real ellipticalEccentricAnomaly, const Real eccentricity)
Converts eccentric anomaly to mean anomaly for elliptical orbits (0 <= eccentricity < 1.0).
This implementation performs a check on the eccentricity and throws an error if it is non-elliptical, i.e., eccentricity < 0.0 and eccentricity >= 1.0.
The equations used can be found in (Chobotov, 2002).
Template Parameters
Real Real type
Parameters
ellipticalEccentricAnomaly Elliptical eccentric anomaly [rad]
eccentricity Eccentricity [-]
Returns
Mean anomaly [rad]
Definition at line 534 of file orbitalElementConversions.hpp.
Referenced by convertEccentricAnomalyToMeanAnomaly().
convertHyperbolicEccentricAnomalyToMeanAnomaly()
template<typename Real > Real astro::convertHyperbolicEccentricAnomalyToMeanAnomaly (const Real hyperbolicEccentricAnomaly, const Real eccentricity)
Converts hyperbolic eccentric anomaly to mean anomaly for hyperbolic orbits (eccentricity > 1.0).
This implementation performs a check on the eccentricity and throws an error if it is non-hyperbolic, i.e., eccentricity >= 1.0.
The equations used can be found in (Chobotov, 2002).
Template Parameters
Real Real type
Parameters
hyperbolicEccentricAnomaly Hyperbolic eccentric anomaly [rad]
eccentricity Eccentricity [-]
Returns
Mean anomaly [rad]
Definition at line 558 of file orbitalElementConversions.hpp.
Referenced by convertEccentricAnomalyToMeanAnomaly().
convertEccentricAnomalyToMeanAnomaly()
template<typename Real > Real astro::convertEccentricAnomalyToMeanAnomaly (const Real eccentricAnomaly, const Real eccentricity)
Converts eccentric anomaly to mean anomaly for elliptical and hyperbolic orbits (eccentricity < 1.0 && eccentricity > 1.0). This function is essentially a wrapper for functions that treat each case. It should be used in cases where the eccentricity of the orbit is not known a priori.
Currently, this implementation performs a check on the eccentricity and throws an error for eccentricity < 0.0 and parabolic orbits, which have not been implemented.
The equations used can be found in (Chobotov, 2002).
See also
convertEllipticalEccentricAnomalyToMeanAnomaly, convertHyperbolicEccentricAnomalyToMeanAnomaly
Template Parameters
Real Real type
Parameters
eccentricity Eccentricity [-]
eccentricAnomaly Eccentric anomaly [rad]
Returns
Mean anomaly [rad]
Definition at line 586 of file orbitalElementConversions.hpp.
References convertEllipticalEccentricAnomalyToMeanAnomaly(), and convertHyperbolicEccentricAnomalyToMeanAnomaly().
convertEllipticalEccentricAnomalyToTrueAnomaly()
template<typename Real > Real astro::convertEllipticalEccentricAnomalyToTrueAnomaly (const Real ellipticEccentricAnomaly, const Real eccentricity)
Converts eccentric anomaly to true anomaly for elliptical orbits (0 <= eccentricity < 1.0). The equations used can be found in (Chobotov, 2002).
Template Parameters
Real Real type
Parameters
ellipticEccentricAnomaly Elliptical eccentric anomaly [rad]
eccentricity Eccentricity [-]
Returns
True anomaly [rad]
Definition at line 622 of file orbitalElementConversions.hpp.
Referenced by convertEccentricAnomalyToTrueAnomaly().
convertHyperbolicEccentricAnomalyToTrueAnomaly()
template<typename Real > Real astro::convertHyperbolicEccentricAnomalyToTrueAnomaly (const Real hyperbolicEccentricAnomaly, const Real eccentricity)
Converts hyperbolic eccentric anomaly to true anomaly for hyperbolic orbits (eccentricity > 1.0). The equations used can be found in (Chobotov, 2002).
Template Parameters
Real Real type
Parameters
hyperbolicEccentricAnomaly Hyperbolic eccentric anomaly [rad]
eccentricity Eccentricity [-]
Returns
True anomaly [rad]
Definition at line 647 of file orbitalElementConversions.hpp.
Referenced by convertEccentricAnomalyToTrueAnomaly().
convertEccentricAnomalyToTrueAnomaly()
template<typename Real > Real astro::convertEccentricAnomalyToTrueAnomaly (const Real eccentricAnomaly, const Real eccentricity)
Converts eccentric anomaly to true anomaly for elliptical and hyperbolic orbits (eccentricity < 1.0 && eccentricity > 1.0). This function is essentially a wrapper for functions that treat each case. It should be used in cases where the eccentricity of the orbit is not known a priori.
Currently, this implementation performs a check on the eccentricity and throws an error for eccentricity < 0.0 and parabolic orbits, which have not been implemented.
The equations used can be found in (Chobotov, 2002).
See also
convertEllipticalEccentricAnomalyToTrueAnomaly, convertHyperbolicEccentricAnomalyToTrueAnomaly
Template Parameters
Real Real type
Parameters
eccentricAnomaly Eccentric anomaly [rad]
eccentricity Eccentricity [-]
Returns
True anomaly [rad]
Definition at line 682 of file orbitalElementConversions.hpp.
References convertEllipticalEccentricAnomalyToTrueAnomaly(), and convertHyperbolicEccentricAnomalyToTrueAnomaly().
computeEllipticalKeplerFunction()
template<typename Real > Real astro::computeEllipticalKeplerFunction (const Real eccentricAnomaly, const Real eccentricity, const Real meanAnomaly)
Computes Kepler function, given as:
for elliptical orbits, where is the eccentric anomaly, is the eccentricity, is the mean anomaly.
This function can be used for root-finding for mean-to-eccentric anomaly conversion.
All elliptical eccentricities >= 0.0 and < 1.0 are valid.
See also
convertEllipticalMeanAnomalyToEccentricAnomaly
Template Parameters
Real Real type
Parameters
eccentricAnomaly Eccentric anomaly [rad]
eccentricity Eccentricity [-]
meanAnomaly Mean anomaly [rad]
Returns
Kepler equation value for given elliptical orbit [rad]
Definition at line 728 of file orbitalElementConversions.hpp.
Referenced by convertEllipticalMeanAnomalyToEccentricAnomaly().
computeFirstDerivativeEllipticalKeplerFunction()
template<typename Real > Real astro::computeFirstDerivativeEllipticalKeplerFunction (const Real eccentricAnomaly, const Real eccentricity)
Computes the 1st-derivative of Kepler function, given as:
for elliptical orbits, where is the eccentric anomaly, and is the eccentricity.
All elliptical eccentricities >= 0.0 and < 1.0 are valid.
Template Parameters
Real Real type
Parameters
eccentricAnomaly Eccentric anomaly [rad]
eccentricity Eccentricity [-]
Returns
First-derivative of Kepler's function for elliptical orbits [rad]
Definition at line 754 of file orbitalElementConversions.hpp.
Referenced by convertEllipticalMeanAnomalyToEccentricAnomaly().
convertEllipticalMeanAnomalyToEccentricAnomaly()
template<typename Real , typename Integer > Real astro::convertEllipticalMeanAnomalyToEccentricAnomaly (const Real eccentricity, const Real meanAnomaly, const Real rootFindingTolerance = 1.0e-3 * std::numeric_limits<Real>::epsilon(), const Integer maximumIterations = 100)
Converts mean anomaly to eccentric anomaly for elliptical orbits, for all eccentricities >= 0.0 and < (1.0 - tolerance).
If the conversion fails or the eccentricity falls outside the valid range, then a runtime exception is thrown.
The tolerance (1.0e-11) for the upper bound of the eccentricty range is based on the fact that the root-finding algorithm struggles with near-parabolic orbits. This is an experimental finding based on extensive research into the behaviour of the root-finding process (Musegaas, 2012).
Also, note that the mean anomaly is automatically transformed to fit within the 0 to 2.0pi range.
See also
computeEllipticalKeplerFunction, computeFirstDerivativeEllipticalKeplerFunction
Template Parameters
Real Real number type
Integer Integer type
Parameters
eccentricity Eccentricity [-]
meanAnomaly Mean anomaly [rad]
rootFindingTolerance Stopping condition tolernace for Newton-Raphson algorithm [rad]
maximumIterations Maximum iteration for Newton-Raphson algorithm [-]
Returns
Eccentric anomaly [rad]
Definition at line 784 of file orbitalElementConversions.hpp.
References computeEllipticalKeplerFunction(), and computeFirstDerivativeEllipticalKeplerFunction().
computeAbsorptionRadiationPressure()
template<typename Real > Real astro::computeAbsorptionRadiationPressure (const Real energyFlux)
Computes radiation pressure for complete absorption from a given energy flux:
where is the computed radiation pressure, is the energy flux, and is the speed of light.
Template Parameters
Real Floating-point type
Parameters
[in] energyFlux Energy flux generated by source, i.e., Sun [W m^-2]
Returns
Computed radiation pressure [N m^-2]
Definition at line 33 of file radiationPressureAccelerationModel.hpp.
References ASTRO_SPEED_OF_LIGHT.
computeRadiationPressure()
template<typename Real > Real astro::computeRadiationPressure (const Real referenceRadiationPressure, const Real referenceDistance, const Real distance)
Computes radiation pressure at a specified distance from the source, e.g., the Sun, by scaling with respect to a given reference. Typically, the reference is taken to be the average energy flux at Earth, i.e., approximately 1 AU.
Since the flux is inversely proportional to the square of the distance, the radiation presurre at a given distance is computed using the following equation:
where is the computed radiation pressure, is the reference radiation pressure, is the reference distance, and is the specified distance.
The distances can be given in any units, so long as they are both in the same units.
Template Parameters
Real Floating-point type
Parameters
[in] referenceRadiationPressure Reference radiation pressure [N m^-2]
[in] referenceDistance Reference distance [AU]
[in] distance Given distance from the Sun [AU]
Returns
Radiation pressure at given distance [N m^-2]
Definition at line 63 of file radiationPressureAccelerationModel.hpp.
computeCannonballRadiationPressureAcceleration()
template<typename Real , typename Vector3 > Vector3 astro::computeCannonballRadiationPressureAcceleration (const Real radiationPressure, const Real radiationPressureCoefficient, const Vector3 & unitVectorToSource, const Real radius, const Real bulkDensity)
Compute radiation pressure acceleration for a canonball. The model for the radiation pressure acceleration is given by (Montenbruck, 2000):
where is the radiation pressure for complete absorption at a specified distance from the source, is the radiation pressure coefficient (for complete absorption and for specular reflection), is the radius of the cannonball, is the bulk density of the cannonball, and is the unit vector pointing to the source of the radiation pressure, e.g., the Sun.
This function can be used to compute the 1st-order effects of radiation pressure on small particles in the Solar System. The higher-order terms, stemming from Poynting-Robertson drag are neglected.
See also
computeCannonballPoyntingRobertsonDragAcceleration
Template Parameters
Real Floating-point type
Vector3 3-vector type
Parameters
[in] radiationPressure Radiation pressure [N m^-2]
[in] radiationPressureCoefficient Radiation pressure coefficient [-]
[in] unitVectorToSource Unit vector pointing to radiation source [-]
[in] radius Radius of cannonball [m]
[in] bulkDensity Bulk density of cannonball [kg m^-3]
Returns
Computed radiation pressure acceleration [m s^-2]
Definition at line 101 of file radiationPressureAccelerationModel.hpp.
computeCannonballPoyntingRobertsonDragAcceleration()
template<typename Real , typename Vector3 > Vector3 astro::computeCannonballPoyntingRobertsonDragAcceleration (const Real radiationPressure, const Real radiationPressureCoefficient, const Vector3 & unitVectorToSource, const Real radius, const Real bulkDensity, const Vector3 & velocity)
Compute Poynting-Roberson (PR) drag acceleration for a cannonball. The model for PR drag acceleration in an inertial reference frame is given by (Mignard, 1984):
where is the radiation pressure for complete absorption at a specified distance from the source, is the radiation pressure coefficient (for complete absorption and for specular reflection), is the radius of the cannonball, is the bulk density of the cannonball, is the unit vector pointing from the source of the radiation pressure, e.g., the Sun, and is the total velocity of the cannonball in an inertial frame centered at the source.
This function can be used to compute the higher-order effects of radiation pressure on small particles in the Solar System. The 1st-order effect (zeroth-order in) is not included.
See also
computeCannonballRadiationPressureAcceleration
Template Parameters
Real Floating-point type
Vector3 3-vector type
Parameters
[in] radiationPressure Radiation pressure [N m^-2]
[in] radiationPressureCoefficient Radiation pressure coefficient [-]
[in] unitVectorToSource Unit vector pointing to radiation source [-]
[in] radius Radius of cannonball [m]
[in] bulkDensity Bulk density of cannonball [kg m^-3]
[in] velocity Total orbital velocity of cannonball wrt inertial centered at radiation source [m s^-1]
Returns
Computed radiation pressure acceleration [m s^-2]
Definition at line 154 of file radiationPressureAccelerationModel.hpp.
References ASTRO_SPEED_OF_LIGHT.
computeKeplerMeanMotion()
template<typename Real > Real astro::computeKeplerMeanMotion (const Real semiMajorAxis, const Real gravitationalParameterOfCentralBody, const Real massOfOrbitingBody = 0.0)
Computes the two-body mean motion of an orbiting body that follows a conic section (Kepler orbit). The mass of the orbiting body is set to that of a test particle by default.
The two-body mean motion is computed as follows:
where is the sum of the gravitational parameters of the two bodies (for the default case of an orbiting test particle, this is the gravitational parameter of the central body) and is the semi-major axis of the Kepler orbit.
Template Parameters
Real Real type
Parameters
semiMajorAxis Semi-major axis of Kepler orbit [m]
gravitationalParameterOfCentralBody Gravitational parameter of central body [m^3 s^-2]
massOfOrbitingBody Mass of orbiting body [kg]
Returns
Two-body mean motion [rad/s]
Definition at line 42 of file twoBodyMethods.hpp.
References ASTRO_GRAVITATIONAL_CONSTANT.
computeKeplerOrbitalPeriod()
template<typename Real > Real astro::computeKeplerOrbitalPeriod (const Real semiMajorAxis, const Real gravitationalParameterOfCentralBody, const Real massOfOrbitingBody = 0.0)
Computes the two-body orbital period of an orbiting body that follows a closed conic section (circle or ellipse Kepler orbit). The mass of the orbiting body is set to that of a test particle by default.
The two-body orbital period is computed as follows:
where is the sum of the gravitational parameters of the two bodies (for the default case of an orbiting test particle, this is the gravitational parameter of the central body) and is the semi-major axis of the Kepler orbit.
Parameters
semiMajorAxis Semi-major axis of Kepler orbit [m]
gravitationalParameterOfCentralBody Gravitational parameter of central body [m^3 s^-2]
massOfOrbitingBody Mass of orbiting body [kg]
Returns
Two-body orbital period [s]
Definition at line 73 of file twoBodyMethods.hpp.
References ASTRO_GRAVITATIONAL_CONSTANT.
computeCircularVelocity()
template<typename Real > Real astro::computeCircularVelocity (const Real semiMajorAxis, const Real gravitationalParameterOfCentralBody)
Computes circular orbital velocity for a (massless) body in a Kepler orbit as follows:
where is the gravitational parameter of the central body) and is the semi-major axis of the Kepler orbit.
If the semi-major axis is zero (to machine precision), an exception is thrown.
Template Parameters
Real Real type
Parameters
semiMajorAxis Semi-major axis of Kepler orbit [m]
gravitationalParameterOfCentralBody Gravitational parameter of central body [m^3 s^-2]
Returns
Circular velocity
Definition at line 103 of file twoBodyMethods.hpp.
Variable Documentation
ASTRO_GRAVITATIONAL_CONSTANT
const double astro::ASTRO_GRAVITATIONAL_CONSTANT = 6.67259e-11 static
Definition at line 16 of file constants.hpp.
Referenced by computeKeplerMeanMotion(), and computeKeplerOrbitalPeriod().
ASTRO_JULIAN_DAY_IN_SECONDS
const double astro::ASTRO_JULIAN_DAY_IN_SECONDS = 86400.0 static
Definition at line 19 of file constants.hpp.
ASTRO_JULIAN_YEAR_IN_DAYS
const double astro::ASTRO_JULIAN_YEAR_IN_DAYS = 365.25 static
Definition at line 22 of file constants.hpp.
ASTRO_JULIAN_YEAR_IN_SECONDS
const double astro::ASTRO_JULIAN_YEAR_IN_SECONDS = 3.15576e7 static
Definition at line 25 of file constants.hpp.
ASTRO_AU_IN_KM
const double astro::ASTRO_AU_IN_KM = 149597870.7 static
Definition at line 28 of file constants.hpp.
ASTRO_GREGORIAN_EPOCH_IN_JULIAN_DAYS
const double astro::ASTRO_GREGORIAN_EPOCH_IN_JULIAN_DAYS = 1721425.5 static
Definition at line 31 of file constants.hpp.
ASTRO_SPEED_OF_LIGHT
const double astro::ASTRO_SPEED_OF_LIGHT = 299792458.0 static
Definition at line 34 of file constants.hpp.
Referenced by computeAbsorptionRadiationPressure(), and computeCannonballPoyntingRobertsonDragAcceleration().